-- Limpar dados antigos de aulas, módulos e junções
DELETE FROM aula_competencia;
DELETE FROM aula_habilidade;
DELETE FROM alternativa;
DELETE FROM pergunta;
DELETE FROM quiz;
DELETE FROM slide;
DELETE FROM atividade;
DELETE FROM video;
DELETE FROM aula;
DELETE FROM modulo;

-- Inserir Módulos do 1º Ano
INSERT INTO modulo (id, serie_id, nome, descricao) VALUES
(1, 1, 'Introdução à Computação', 'Fundamentos conceituais, histórico e áreas da computação.'),
(2, 1, 'Conhecendo o Computador', 'Componentes de hardware, software, periféricos e preservação ambiental.'),
(3, 1, 'Internet', 'Funcionamento técnico da internet, serviços digitais e inclusão social.'),
(4, 1, 'Segurança Digital', 'Estratégias de proteção pessoal, combate a golpes e fake news.'),
(5, 1, 'Cidadania Digital', 'Ética na rede, saúde mental, cyberbullying e direitos autorais.'),
(6, 1, 'Projeto Final — Minha Primeira Investigação Digital', 'Aplicação prática dos conceitos fundamentais de cidadania digital e investigação.');

-- Inserir Módulos do 2º Ano
INSERT INTO modulo (id, serie_id, nome, descricao) VALUES
(7, 2, 'Hardware na Prática', 'Arquitetura física detalhada de computadores e smartphones.'),
(8, 2, 'Sistemas Operacionais e Softwares', 'Gerenciamento de softwares, interfaces de usuários e extensões de arquivos.'),
(9, 2, 'Pensamento Computacional', 'Os quatro pilares da lógica computacional e fluxogramas.'),
(10, 2, 'Tecnologia para Estudo e Trabalho', 'Uso produtivo e colaborativo de ferramentas de texto, planilha e slides.'),
(11, 2, 'Produção Digital', 'Criação e edição básica de mídias de vídeo, áudio, podcasts e imagens.'),
(12, 2, 'Projeto Final — Resolução de Problemas no Cotidiano', 'Resolução de problemas do cotidiano escolar aplicando lógica computacional.');

-- Inserir Módulos do 3º Ano
INSERT INTO modulo (id, serie_id, nome, descricao) VALUES
(13, 3, 'Inteligência Artificial', 'Histórico, Machine Learning, IA Generativa e dilemas éticos da automação.'),
(14, 3, 'Desenvolvimento de Soluções Digitais', 'Ciclo de vida de software, conceitos básicos de web e plataformas no-code.'),
(15, 3, 'Segurança da Informação', 'Leis de proteção de dados (LGPD), engenharia social, malwares e backup.'),
(16, 3, 'Tecnologia e Sociedade', 'Efeitos socioculturais da automação, deepfakes, sustentabilidade e dependência digital.'),
(17, 3, 'Profissões em Tecnologia', 'Mapeamento de carreiras em TI, formação acadêmica e mercado de trabalho.'),
(18, 3, 'Projeto Final — Cidadão Digital e Soluções Tecnológicas', 'Modelagem, ética e prototipagem de uma solução digital para impacto social.');

-- Inserir Aulas do Módulo 1 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(101, 1, 'O que é Computação?', 'Apresentação dos conceitos básicos sobre computação e dados. Os alunos entenderão que computar significa calcular e processar, indo muito além de apenas acessar redes sociais ou navegar no celular.', 1, 'Compreender a diferença entre usar aparelhos digitais e a ciência da Computação, reconhecendo a computação como o processamento sistemático de informações.', 'Projetor ou TV, quadro escolar, caderno e caneta.', '50 minutos'),
(102, 1, 'A História da Computação: Da Contagem aos Supercomputadores', 'Um passeio histórico que vai do ábaco e das máquinas mecânicas de calcular ao surgimento do ENIAC, computadores pessoais e o papel fundamental de pioneiros como Ada Lovelace e Grace Hopper.', 2, 'Reconhecer a evolução histórica das ferramentas de cálculo e processamento até a criação dos computadores modernos, valorizando as contribuições de pioneiros.', 'Projetor ou TV para exibição de imagens históricas, quadro escolar.', '50 minutos'),
(103, 1, 'Como os Computadores Processam: Introdução ao Binário', 'Uma aula prática e desplugada que usa cartões ou lâmpadas desenhadas para demonstrar o sistema binário de maneira visual. Discussão sobre mitos do cotidiano envolvendo computadores.', 3, 'Compreender o conceito de código binário (0 e 1) e como os computadores representam números, letras e imagens.', 'Cartões de papel numerados potências de 2, quadro escolar.', '50 minutos'),
(104, 1, 'Áreas da Computação e Profissões', 'Uma introdução descomplicada às grandes áreas da computação, desmistificando o mercado de trabalho e mostrando onde os diferentes perfis se encaixam na criação de tecnologia.', 4, 'Conhecer as subdivisões da ciência da computação (hardware, software, redes, IA, segurança) e a atuação profissional de cada uma.', 'Projetor ou TV, quadro escolar.', '50 minutos');

-- Inserir Aulas do Módulo 2 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(105, 2, 'O Corpo e a Mente: Hardware vs. Software', 'Utilizando analogias simples, os alunos entenderão a diferença conceitual e a interdependência entre a parte física e lógica de computadores e smartphones, analisando o ciclo de processamento de dados.', 1, 'Distinguir os componentes físicos (hardware) das instruções lógicas (software) e compreender o ciclo básico de entrada, processamento e saída.', 'Projetor ou TV, quadro escolar.', '50 minutos'),
(106, 2, 'Interagindo com o Computador: Dispositivos de Entrada e Saída', 'Estudo sobre teclados, mouses, microfones, câmeras, monitores e fones de ouvido. Discussão prática sobre o desenvolvimento de periféricos voltados para tecnologias assistivas.', 2, 'Identificar os dispositivos de entrada e saída, compreendendo seu papel na interação humano-computador e sua relevância para a acessibilidade.', 'Periféricos antigos (opcional), projetor ou TV, quadro.', '50 minutos'),
(107, 2, 'Armazenamento e Memória: RAM vs. SSD vs. HD', 'Explicação prática sobre como a informação é guardada de forma temporária e permanente. Análise visual de peças físicas e discussões sobre o impacto da evolução da velocidade no uso diário.', 3, 'Diferenciar a memória de trabalho (RAM) dos dispositivos de armazenamento permanente (HD, SSD e Pendrive), compreendendo suas hierarquias de velocidade.', 'Amostras ou fotos de HDs mecânicos e SSDs, projetor ou TV.', '50 minutos'),
(108, 2, 'Preservação, Higiene e Obsolescência Programada', 'Dicas preventivas de limpeza e temperatura de computadores e celulares. Debate sobre a vida útil dos aparelhos, o impacto ambiental da obsolescência programada e descarte correto.', 4, 'Aprender práticas de conservação física de eletrônicos e refletir criticamente sobre o descarte e o consumismo de tecnologia (lixo eletrônico).', 'Quadro escolar, notícias ou folheto sobre lixo eletrônico.', '50 minutos');

-- Inserir Aulas do Módulo 3 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(109, 3, 'O que é a Internet e Como Ela Surgiu?', 'Desmistificação da internet mostrando os cabos gigantescos submarinos e os data centers ("nuvem") que guardam e processam nossos arquivos, relacionando ao contexto histórico do surgimento das redes.', 1, 'Compreender a internet como uma rede física global de computadores interconectados e conhecer sua origem e a infraestrutura de nuvem.', 'Projetor ou TV para exibição do mapa de cabos submarinos, quadro.', '50 minutos'),
(110, 3, 'Navegando na Web: URLs, Navegadores e Pesquisas', 'Explicação de como o navegador traduz código em páginas web. Análise de URLs para segurança e aplicação de truques úteis de motores de busca (aspas, formatos de arquivos) para pesquisas escolares.', 2, 'Compreender a função dos navegadores de internet, a estrutura básica de um link (URL) e aplicar técnicas avançadas de pesquisa.', 'Projetor ou TV, quadro escolar.', '50 minutos'),
(111, 3, 'Como a Informação Viaja: Roteamento e Serviços Digitais', 'Dinâmica prática de roteamento teatral usando envelopes. Em seguida, análise de serviços de e-mail, mapas, streaming e utilidades públicas digitais (Gov.br).', 3, 'Entender o conceito de roteamento, pacotes de dados e IPs, e mapear os principais serviços web do cotidiano.', 'Papéis e envelopes (dinâmica teatral), projetor ou TV.', '50 minutos'),
(112, 3, 'Inclusão Digital e o Direito à Conexão', 'Discussão sobre as diferenças de conectividade no Brasil (velocidade, franquia e tela) e como a falta de acesso compromete os estudos e oportunidades profissionais.', 4, 'Refletir criticamente sobre as barreiras socioeconômicas de acesso à internet de qualidade e como a exclusão afeta a cidadania.', 'Gráficos e dados sobre inclusão digital (projetados ou impressos).', '50 minutos');

-- Inserir Aulas do Módulo 4 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(113, 4, 'Chaves Digitais: Senhas Fortes e Privacidade', 'Dinâmica de criação de senhas difíceis de hackear mas fáceis de lembrar. Discussão sobre o valor comercial das informações privadas e configurações de segurança de aplicativos.', 1, 'Criar senhas pessoais robustas, compreender a verificação em duas etapas e ajustar as restrições de privacidade nas redes sociais.', 'Quadro escolar, papel e caneta para rascunhos.', '50 minutos'),
(114, 4, 'Golpes Digitais e Engenharia Social (Phishing)', 'Análise de mensagens reais de golpistas (phishing) e fraudes comuns (PIX agendado, clonagem de contas no WhatsApp). Os alunos aprenderão a buscar pistas de adulterações.', 2, 'Identificar links, e-mails e mensagens fraudulentas estruturados para roubar dados ou aplicar golpes financeiros cotidianos.', 'Prints de mensagens/e-mails suspeitos projetados ou impressos.', '50 minutos'),
(115, 4, 'Desinformação e Combate a Fake News', 'Como as Fake News são escritas para despertar fortes reações emocionais. Passos práticos para checar notícias usando agências de checagem e análise de fontes.', 3, 'Desenvolver uma postura analítica e crítica para identificar boatos e desinformações nas redes.', 'Exemplos históricos de boatos virtuais projetados ou impressos.', '50 minutos'),
(116, 4, 'Proteção de Dispositivos e Segurança Familiar', 'Cuidados de conexões e concessão de acesso a recursos físicos do celular (câmera, contatos). Trabalho em grupo para criar cartazes informativos com dicas de segurança para familiares.', 4, 'Aprender os perigos de redes Wi-Fi públicas, gerenciar permissões de apps e planejar cartilhas de orientação digital.', 'Papel cartolina, canetas coloridas, tesoura e cola.', '50 minutos');

-- Inserir Aulas do Módulo 5 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(117, 5, 'Convivência Ética e Netiqueta nas Redes Sociais', 'Reflexão sobre como as redes retêm nossa atenção. Boas práticas de convivência digital, netiqueta para escrita construtiva e como identificar e acolher vítimas de assédio online.', 1, 'Analisar criticamente as bolhas de informação, os algoritmos de engajamento e combater a violência oculta do Cyberbullying.', 'Histórias hipotéticas de conflitos online para debate em grupo.', '50 minutos'),
(118, 5, 'Autoria na Internet: Direitos Autorais e Plágio', 'Plágio e pirataria na rede e como dar créditos corretos em pesquisas. Introdução a conteúdos livres e às regras simples de licenciamento gratuito para produções autorais.', 2, 'Compreender as regras de direitos autorais, diferenciar plágio de pesquisa científica e aplicar o licenciamento Creative Commons.', 'Exemplos de licenças de uso Creative Commons, quadro.', '50 minutos'),
(119, 5, 'Pegada Digital e Saúde Mental', 'Debate sobre pegada digital e a análise de redes sociais em processos seletivos. Análise de ansiedade provocada por feeds, luz azul e dependência de curtidas.', 3, 'Compreender o rastro permanente gerado por publicações digitais e criar estratégias para mitigar a dependência das telas.', 'Ficha de autoavaliação sobre tempo de uso de celulares.', '50 minutos'),
(120, 5, 'Ativismo e Cidadania Ativa Digital', 'Uso de ferramentas web para participação social, como abaixo-assinados digitais, fiscalização de problemas do bairro e mobilização legítima para melhorias escolares.', 4, 'Identificar formas construtivas de utilizar a internet em prol da sociedade local.', 'Projetor ou TV, papel para planejamento de ação social escolar.', '50 minutos');

-- Inserir Aulas do Módulo 6 (1º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(121, 6, 'Concepção do Projeto e Pesquisa de Opinião', 'Definição dos temas integradores (segurança, fake news, lixo eletrônico, exclusão). Os grupos formulam questionários de pesquisa simples para aplicar a familiares.', 1, 'Organizar grupos, delimitar um problema digital local e estruturar perguntas para coleta de dados.', 'Quadro escolar, folhas de papel e canetas.', '50 minutos'),
(122, 6, 'Coleta de Dados e Compilação das Respostas', 'Os alunos trazem as pesquisas aplicadas. Discussão e tabulação de dados no caderno para entender as principais dores digitais da vizinhança.', 2, 'Tabular os resultados colhidos nas pesquisas externas e extrair conclusões estatísticas iniciais.', 'Questionários preenchidos, cadernos para tabulação de dados.', '50 minutos'),
(123, 6, 'Planejamento e Confecção do Material', 'Desenvolvimento prático de cartazes ou folhetos informativos usando cartolinas. Organização do texto explicativo de prevenção para que seja direto e atrativo.', 3, 'Planejar o layout informativo e produzir as peças artísticas físicas da campanha.', 'Cartolinas ou papel sulfite, canetas hidrográficas coloridas.', '50 minutos'),
(124, 6, 'Apresentação da Campanha e Feedback', 'Apresentação dos cartazes para a turma. Exposição no mural da escola e debate cooperativo sobre a recepção da comunidade aos temas de Educação Digital.', 4, 'Expor os materiais produzidos na escola e debater os aprendizados sobre cidadania digital.', 'Fitas adesivas, mural escolar ou quadro de exposição.', '50 minutos');

-- Inserir Aulas do Módulo 7 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(201, 7, 'A Placa-Mãe e as Conexões do PC', 'Uma explicação visual sobre onde os componentes do computador se encaixam e como as trilhas e os fios (barramentos) transportam energia e dados elétricos de um lugar para o outro.', 1, 'Conhecer a placa-mãe como a central de interconexão física de todos os dispositivos do computador e barramento de dados.', 'Projetor ou TV para fotos de alta resolução de placas-mãe, quadro escolar.', '50 minutos'),
(202, 7, 'A Força Bruta de Processamento: A CPU e Refrigeração', 'Explicação de termos técnicos como "núcleos" (cores), velocidade em GHz e cooler para manter o chip funcionando sem travar.', 2, 'Entender a função profunda do processador, fatores que definem o seu rendimento básico e a importância da dissipação de calor.', 'Projetor ou TV, quadro.', '50 minutos'),
(203, 7, 'Memórias e Armazenamento: RAM vs. SSD vs. HD', 'Análise prática de como a transição de HDs para SSDs mudou a velocidade de inicialização do sistema e de aplicativos, mostrando a hierarquia e taxas de velocidade de cada memória.', 3, 'Compreender a diferença de velocidade e funcionalidade entre os tipos de memórias no acesso diário de arquivos.', 'Amostras ou fotos de HDs mecânicos e SSDs, projetor ou TV.', '50 minutos'),
(204, 7, 'GPU, Energia e Diagnósticos de Problemas', 'Placas dedicadas vs. integradas. Fonte de alimentação e energia estável. Como diagnosticar problemas de superaquecimento ou memória a partir de sons (apitos) ou desligamento repentino.', 4, 'Compreender a função da placa de vídeo (GPU), fontes de alimentação e identificar defeitos físicos simples.', 'Quadro escolar, projetor ou TV.', '50 minutos');

-- Inserir Aulas do Módulo 8 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(205, 8, 'O Maestro Virtual: SO e Interfaces (Windows vs. Linux)', 'O papel do SO em organizar a memória, tarefas e programas. Comparativo de filosofias, segurança e gratuidade de sistemas Windows e Linux.', 1, 'Compreender o Sistema Operacional como o programa principal que traduz as ações do usuário em controle do hardware, e diferenciar interfaces comerciais de código aberto.', 'Capturas de tela das áreas de trabalho dos sistemas Windows e Linux projetadas.', '50 minutos'),
(206, 8, 'Sistemas Móveis e Aplicativos', 'Funcionamento de aparelhos móveis: controle de consumo de bateria, atualizações de aplicativos em segundo plano e a importância do download em fontes seguras.', 2, 'Reconhecer a arquitetura dos sistemas operacionais de celulares (Android e iOS), o papel de lojas oficiais e gerência de processos.', 'Projetor ou TV, quadro escolar.', '50 minutos'),
(207, 8, 'Arquivos, Pastas e Instalação de Programas', 'A diferença entre arquivos executáveis (.exe, .deb, .apk) e pastas comuns. Exercício de organização de arquivos em estrutura em árvore para fins escolares.', 3, 'Compreender a lógica de instalação de programas, identificar extensões de arquivos (.docx, .pdf, .png) e organizar diretórios lógicos.', 'Quadro escolar, projetor ou TV.', '50 minutos'),
(208, 8, 'Manutenção Preventiva e Sistemas em Nuvem', 'Limpeza lógica de arquivos temporários, desinstalação de programas inúteis e a apresentação de sistemas operacionais focados na web (como o ChromeOS).', 4, 'Reconhecer a importância das atualizações de segurança do sistema e o conceito de sistemas operacionais baseados na nuvem.', 'Projetor ou TV, quadro escolar.', '50 minutos');

-- Inserir Aulas do Módulo 9 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(209, 9, 'Introdução ao Pensamento Computacional e Decomposição', 'Introdução ao Pensamento Computacional. Dinâmica cooperativa: desmembrar problemas ou projetos complexos (como organizar um festival escolar) em pequenas etapas resolvíveis.', 1, 'Conhecer a importância do raciocínio lógico no planejamento de soluções e aplicar o pilar da decomposição.', 'Fichas de tarefas impressas, quadro escolar.', '50 minutos'),
(210, 9, 'Reconhecimento de Padrões e Abstração', 'Padrões lúdicos no cotidiano para reutilizar soluções. Exercício prático de abstração usando mapas de trânsito simplificados e seleção de dados fundamentais.', 2, 'Identificar repetições ou semelhanças em dados e focar em informações úteis eliminando detalhes desnecessários.', 'Mapas de metrô ou textos detalhados para exercício em folha.', '50 minutos'),
(211, 9, 'Criando Roteiros Lógicos: Algoritmos no Cotidiano', 'Escrita de receitas lógicas e comandos sequenciais (como o algoritmo exato para amarrar o sapato ou desenhar no papel), desafiando colegas a seguirem à risca as instruções.', 3, 'Desenvolver sequências estruturadas de passos de forma clara e linear, sem ambiguidades.', 'Papel e caneta para escrita dos passos lógicos.', '50 minutos'),
(212, 9, 'Fluxogramas e Desafios de Lógica Desplugada', 'Uso de caixas de início, ação, decisões (Sim/Não) e fim. Competição cooperativa de desafios e charadas matemáticas desplugadas de forma lógica e rápida.', 4, 'Representar graficamente fluxos de decisões lógicas por meio de blocos geométricos e resolver enigmas aplicando os quatro pilares.', 'Quadro escolar, folhas com enigmas impressos.', '50 minutos');

-- Inserir Aulas do Módulo 10 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(213, 10, 'Edição e Formatação de Textos Acadêmicos', 'Estruturação de um documento: margens, espaçamentos, títulos, sumários e como referenciar fontes bibliográficas de forma limpa em processadores de texto.', 1, 'Formatar relatórios e textos escolares seguindo diretrizes estruturais básicas de digitação (ABNT).', 'Projetor ou TV com editor de texto aberto para demonstração das ferramentas.', '50 minutos'),
(214, 10, 'Planilhas Eletrônicas e Visualização de Dados', 'Introdução ao uso de tabelas digitais para notas escolares e finanças pessoais. Geração de gráficos de pizza, barras e linhas para análises rápidas e eficientes.', 2, 'Compreender a estrutura de células e fórmulas aritméticas simples (soma, média) e converter dados numéricos em gráficos explicativos.', 'Projetor ou TV demonstrando planilha aberta, quadro escolar.', '50 minutos'),
(215, 10, 'Design de Apresentações de Slides', 'Regras básicas de contraste de cores, tamanho de fontes legíveis, uso de tópicos pontuais, inserção de imagens explicativas e técnicas corporais básicas de apresentação de ideias.', 3, 'Projetar apresentações visuais harmônicas e equilibradas, fugindo do excesso de textos.', 'Exemplos de slides bons e ruins projetados.', '50 minutos'),
(216, 10, 'Trabalho Coletivo, Calendários e Portfólio', 'Armazenamento e comentários compartilhados online. Uso prático de agendas eletrônicas e listas de tarefas. Compilação de relatórios e fotos em pastas digitais estruturadas.', 4, 'Editar documentos em nuvem colaborativamente, gerenciar prazos em agendas virtuais e montar portfólios organizados de atividades do ano.', 'Projetor ou TV, quadro, computador de demonstração.', '50 minutos');

-- Inserir Aulas do Módulo 11 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(217, 11, 'Comunicação Visual e Editores Gráficos', 'Fundamentos de design de cartaz: posicionamento de elementos, paleta de cores harmoniosa, seleção de imagens de boa qualidade e escrita de chamadas textuais curtas e chamativas.', 1, 'Criar peças visuais básicas (cartazes e banners) utilizando ferramentas online e gratuitas de design.', 'Projetor ou TV, celulares dos alunos (se permitido) ou atividade com recortes.', '50 minutos'),
(218, 11, 'Planejamento, Gravação e Edição de Vídeo', 'Elaboração de roteiro de 2 minutos. Como usar iluminação solar caseira. Uso de aplicativos mobile gratuitos de corte e legendagem de vídeos.', 2, 'Estruturar roteiros simples de vídeo explicativo, aplicar enquadramentos de celular e dominar edições básicas de corte e transição.', 'Celular com app de edição instalado (opcional), papel para roteiro.', '50 minutos'),
(219, 11, 'Planejamento e Edição de Áudio (Podcasts)', 'Estrutura dinâmica de perguntas e vinhetas. Gravação limpa de som no celular. Ajustes de volume de voz em relação à música de fundo em aplicativos.', 3, 'Compreender o formato de podcast, planejar roteiros de entrevistas e editar trilhas e vozes.', 'Amostra de áudio de podcast educacional, projetor ou TV.', '50 minutos'),
(220, 11, 'Direitos Autorais, Imagem e Curadoria Ética', 'Proteção e compartilhamento legal de vídeos escolares. Cuidados de privacidade em relação a rostos alheios. Como comentar e compartilhar indicações de conteúdo na rede.', 4, 'Publicar produções em Creative Commons de forma ética, respeitando imagens alheias e realizando curadorias informativas de links.', 'Quadro escolar, ilustrações das regras Creative Commons.', '50 minutos');

-- Inserir Aulas do Módulo 12 (2º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(221, 12, 'Identificação de Gargalos e Modelagem Lógica', 'Mapeamento de problemas cotidianos da escola (filas, biblioteca, salas de estudo). Os grupos rascunham o fluxo de ação e decisões para otimizá-lo.', 1, 'Identificar gargalos da rotina escolar, escolher o tema integrador e modelar o fluxo lógico da solução.', 'Quadro escolar, cadernos e lápis.', '50 minutos'),
(222, 12, 'Prototipação em Papel das Interfaces (Wireframes)', 'Desenvolvimento prático das telas. Como o usuário veria as informações? Rascunhos de botões, formulários e textos explicativos utilizando cartões de cartolina ou papel sulfite.', 2, 'Desenhar de forma desplugada as telas de um aplicativo fictício ou os cartazes de fluxo para os usuários.', 'Papel sulfite, lápis, canetas, tesouras e réguas.', '50 minutos'),
(223, 12, 'Projeção de Dados e Conclusão Artística', 'Cálculos fictícios de tempos e recursos economizados na escola com o projeto. Finalização dos livretos ou cartazes contendo a identidade do trabalho.', 3, 'Tabular dados estatísticos dos benefícios projetados da solução e concluir o material demonstrativo físico.', 'Cartolinas, marcadores, réguas e calculadoras.', '50 minutos'),
(224, 12, 'O Pitch do Projeto: Apresentação para a Turma', 'Apresentação dinâmica das ideias simulando pitches corporativos de utilidade escolar. A sala debate a viabilidade e sugere melhorias aos grupos.', 4, 'Comunicar a ideia do projeto de forma sucinta (pitch de 3 minutos) e receber feedback construtivo dos colegas.', 'Cronômetro de tempo de apresentação, quadro escolar.', '50 minutos');

-- Inserir Aulas do Módulo 13 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(301, 13, 'O Despertar da IA: Histórico e Conceito Básico', 'Apresentação da IA, diferenciando robôs de filmes de ficção científica de sistemas lógicos reais baseados em algoritmos matemáticos complexos. Apresentação do clássico teste de Turing.', 1, 'Compreender o que define a Inteligência Artificial e conhecer momentos marcantes do seu surgimento científico.', 'Projetor ou TV, quadro escolar.', '50 minutos'),
(302, 13, 'Como as Máquinas Aprendem: Machine Learning e Redes Sociais', 'Como dados históricos são usados para treinar sistemas sem código rígido. Discussão prática sobre a captura de curtidas e tempo de visualização de telas que retroalimentam algoritmos.', 2, 'Compreender conceitualmente o aprendizado de máquina a partir de dados e mapear as aplicações de recomendação invisíveis nas redes sociais.', 'Projetor ou TV, quadro escolar.', '50 minutos'),
(303, 13, 'Inteligência Artificial Generativa e Prompting', 'A geração automatizada de conhecimento e o funcionamento de grandes redes. Como conversar com a IA usando instruções ricas e a importância de supervisionar dados inventados.', 3, 'Entender o funcionamento de modelos geradores de textos/imagens, aprender a redigir instruções eficazes (prompts) e prever alucinações das ferramentas.', 'Celulares dos alunos (se permitido), projetor de demonstração.', '50 minutos'),
(304, 13, 'Ética, Vieses de Dados e o Futuro do Trabalho', 'Debate sobre erros em identificação facial ou seleções de emprego gerados por dados enviesados históricos. Mapeamento das tarefas humanas que tendem a ser automatizadas e as novas carreiras.', 4, 'Analisar preconceitos algorítmicos em decisões automatizadas e refletir sobre a transição profissional devido à automação.', 'Casos jornalísticos impressos ou projetados sobre erros algorítmicos.', '50 minutos');

-- Inserir Aulas do Módulo 14 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(305, 14, 'O Ciclo de Desenvolvimento de Software', 'Uma explicação voltada à gestão de projetos. Os estudantes entenderão que programar é apenas uma das etapas da criação de um produto digital útil e funcional.', 1, 'Conhecer o ciclo de vida do desenvolvimento de um programa (análise de problemas, design, programação, testes e sustentação).', 'Projetor ou TV, quadro.', '50 minutos'),
(306, 14, 'O Esqueleto da Web e Aplicativos Móveis', 'A analogia das paredes da casa (HTML), pintura (CSS) e lógica elétrica (JS). Como celulares (clientes) se comunicam com servidores distantes para carregar dados de telas de forma dinâmica.', 2, 'Entender conceitualmente a função de HTML, CSS e JavaScript e a arquitetura cliente-servidor (front-end e back-end).', 'Quadro escolar, projetor ou TV.', '50 minutos'),
(307, 14, 'Equipes de Tecnologia e Metodologias Ágeis', 'Apresentação de profissionais de UX/UI, gerentes de produto, desenvolvedores e QAs. Dinâmica de estruturação de quadro Kanban físico ("A Fazer", "Fazendo", "Feito") usando post-its.', 3, 'Conhecer os diferentes papéis de especialistas de TI e organizar tarefas de grupo em quadros ágeis (Kanban).', 'Notas autoadesivas coloridas (post-its) ou fita crepe, quadro.', '50 minutos'),
(308, 14, 'Criação Rápida de Soluções com No-Code', 'Demonstração de construtores visuais de blogs e sites gratuitos. Reflexão sobre como essas tecnologias abrem portas para o empreendedorismo social rápido e de baixo custo.', 4, 'Conhecer o potencial de ferramentas visuais sem código para validação ágil de páginas informativas e portfólios.', 'Projetor ou TV demonstrando ferramentas visuais de criação de sites.', '50 minutos');

-- Inserir Aulas do Módulo 15 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(309, 15, 'Dados Pessoais, Privacidade e a LGPD', 'A economia dos dados e anúncios direcionados de serviços gratuitos. Estudo dos direitos de exclusão de dados e da finalidade do consentimento de cookies nos sites.', 1, 'Compreender o valor financeiro das informações pessoais no mercado de anúncios digitais e os direitos assegurados pela LGPD.', 'Trechos simplificados e explicados da LGPD (impressos ou projetados).', '50 minutos'),
(310, 15, 'Engenharia Social, Phishing e Defesas', 'Senhas fortes combinadas com códigos de segurança (2FA). A engenharia social baseada em senso de urgência falsa e o combate a iscas digitais que induzem à entrega voluntária de acessos.', 2, 'Identificar táticas de manipulação psicológica usadas em fraudes e aplicar chaves de dupla autenticação.', 'Transcrições ou áudios de golpes digitais reais.', '50 minutos'),
(311, 15, 'Ameaças Virtuais (Malwares) e Criptografia', 'O perigo de vírus, cavalos de troia e ransomwares (sequestro de arquivos). Como chaves públicas e privadas protegem transações e o tráfego em redes de Wi-Fi públicas via cadeado do navegador.', 3, 'Classificar softwares maliciosos comuns e compreender conceitualmente o papel da criptografia.', 'Envelopes e chaves físicas de demonstração lógica, quadro.', '50 minutos'),
(312, 15, 'Rotinas de Backup e Planos de Emergência', 'Cópias seguras em mídias e nuvens diferentes. Elaboração de um manual do que fazer ao ter contas clonadas: boletim de ocorrência online, contato com bancos e notificação a familiares.', 4, 'Aplicar a regra do backup seguro 3-2-1 e estruturar um roteiro prático de contingência em caso de roubo de dados.', 'Ficha estruturada para preenchimento do plano de emergência, quadro.', '50 minutos');

-- Inserir Aulas do Módulo 16 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(313, 16, 'Inclusão Digital e Sustentabilidade Ecológica', 'Dificuldade de acesso a serviços públicos. A pegada de carbono de servidores de IA e streamings e o perigo do lixo eletrônico tóxico (chumbo/mercúrio) em aterros locais.', 1, 'Debater as dificuldades da exclusão digital e o impacto energético/ambiental gerado por computadores e descarte.', 'Infográficos ambientais de tecnologia e dados de exclusão.', '50 minutos'),
(314, 16, 'Saúde Mental e Dependência Tecnológica', 'O vício invisível de telas e likes. Discussão aberta sobre FOMO, insônia e ansiedade motivada pela comparação constante nas redes de influenciadores, aplicando regras de autocontrole.', 2, 'Avaliar o impacto das notificações, loops de dopamina das redes e propor hábitos equilibrados de desconexão.', 'Quadro escolar, folhas para relatos anônimos da turma.', '50 minutos'),
(315, 16, 'Deepfakes, Desinformação e Vieses Automatizados', 'Deepfakes criminosas e formas de detectá-las. Análise de sistemas automáticos que decidem financiamentos ou sentenças judiciais sem auditorias ou explicações humanas claras.', 3, 'Reconhecer manipulações visuais e sonoras complexas criadas por IAs e os riscos decorrentes para a democracia e imagem de pessoas comuns.', 'Imagens ou vídeos manipulados para análise de imperfeições.', '50 minutos'),
(316, 16, 'Leis Digitais e a Governança das Redes', 'As leis brasileiras relativas a crimes cibernéticos de invasão. Discussão sobre a responsabilidade de plataformas em combater discursos nocivos sem infringir a liberdade de expressão.', 4, 'Conhecer o Marco Civil da Internet no Brasil, a Lei Carolina Dieckmann e os debates democráticos sobre regulação das mídias.', 'Projetor ou TV, quadro escolar.', '50 minutos');

-- Inserir Aulas do Módulo 17 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(317, 17, 'Mapeando os Cursos de TI (Computação, Software e Sistemas)', 'Comparativo simples de Ciência da Computação (foco em algoritmos/pesquisa), Engenharia de Software (processos de criação de código e projetos) e Sistemas de Informação (gestão tecnológica).', 1, 'Compreender as diferenças curriculares e atuações profissionais de graduações em TI.', 'Projetor ou TV, grades curriculares resumidas no quadro.', '50 minutos'),
(318, 17, 'Interfaces e Infraestrutura: UX/UI, Redes e Cibersegurança', 'O design focado em empatia e acessibilidade de cores e telas. O trabalho crítico de manter servidores no ar e protegidos contra invasores externos corporativos.', 2, 'Conhecer a rotina profissional de designers de experiência de usuário e de administradores/defensores de redes de computadores.', 'Exemplos de layouts responsivos projetados, quadro.', '50 minutos'),
(319, 17, 'O Mundo dos Dados e IA: Ciência de Dados e Engenharia de IA', 'O trabalho de cientistas de dados gerando estatísticas preditivas para medicina ou comércio. Novas carreiras de treinamento e refino de modelos de Inteligência Artificial.', 3, 'Compreender as novas carreiras de análise de grandes volumes de informações, prompt engineering e modelagem inteligente de algoritmos.', 'Projetor ou TV, gráficos estatísticos corporativos.', '50 minutos'),
(320, 17, 'Portfólio e Educação Continuada', 'Como o profissional de tecnologia se mantém atualizado. Apresentação de plataformas públicas de exibição de projetos pessoais para contratação profissional futura.', 4, 'Planejar passos de desenvolvimento profissional, conhecendo cursos livres, certificações técnicas e formas de divulgar conhecimentos.', 'Exemplos de páginas de portfólios acadêmicos e técnicos projetados.', '50 minutos');

-- Inserir Aulas do Módulo 18 (3º Ano)
INSERT INTO aula (id, modulo_id, titulo, descricao, ordem, objetivo, recursos_necessarios, duracao_sugerida) VALUES
(321, 18, 'Concepção de Projetos Sociais Tecnológicos', 'Formação dos grupos e rascunho de soluções tecnológicas de utilidade pública baseadas em problemas reais da própria vizinhança ou escola.', 1, 'Escolher um problema ético, ecológico ou de inclusão digital da comunidade local para propor uma solução de utilidade pública.', 'Quadro escolar, folhas de papel e canetas.', '50 minutos'),
(322, 18, 'Fluxograma e Arquitetura da Solução', 'Desenho no papel cartolina de fluxogramas funcionais completos que detalham o caminho exato de funcionamento da solução idealizada pelo grupo.', 2, 'Esquematizar de forma detalhada o fluxo de dados (entrada, processamento, saída) e as decisões lógicas do projeto.', 'Papel cartolina, réguas e marcadores coloridos.', '50 minutos'),
(323, 18, 'Viabilidade Ética, Legal (LGPD) e Acessibilidade', 'Debate de segurança de dados: onde as informações ficam guardadas? Como o usuário pede a exclusão? Adaptação de contrastes e recursos táteis no projeto.', 3, 'Analisar a conformidade legal do projeto com a LGPD e desenhar soluções para usuários com deficiência auditiva ou visual.', 'Ficha de checklist ético legal, quadro.', '50 minutos'),
(324, 18, 'Criação de Protótipo e Feira Tecnológica', 'Elaboração de telas mobile interativas desenhadas. Exposição final de cartazes simulando fluxos de serviço para a comunidade escolar e colegas de classe.', 4, 'Produzir protótipos de papel de telas de simulação e expor os trabalhos em feira de ciências.', 'Cartolinas, tesouras, cola e fitas adesivas para fixação.', '50 minutos');

-- Atualizar sequências pós inserts estáticos
SELECT setval('modulo_id_seq', 18);
SELECT setval('aula_id_seq', 324);
